xname: ptf-app
region: bga

services:
  - name: frontend
    environment_slug: node-js
    source_dir: frontend
    github:
      repo: am-muhwezi/ptf
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    routes:
      - path: /

  - name: backend
    environment_slug: python
    source_dir: backend
    github:
      repo: am-muhwezi/ptf
      branch: main
      deploy_on_push: true
    # Remove static files collection since you don't need them
    build_command: >
      pip install -r requirements.txt &&
      python manage.py migrate
    # Match your Procfile exactly
    run_command: gunicorn ptf.wsgi:application --log-file -
    routes:
      - path: /api
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: ptf.settings
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        value: changeme-secret-key
      - key: ALLOWED_HOSTS
        value: ${APP_DOMAIN}