name: ptf-app
region: bga # Change to your region: nyc, sfo, sgp, etc.

services:
  - name: frontend
    environment_slug: node-js
    source_dir: frontend
    github:
      repo: am-muhwezi/ptf
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    output_dir: build
    routes:
      - path: /

  - name: backend
    environment_slug: python
    source_dir: backend
    github:
      repo: am-muhwezi/ptf
      branch: main
      deploy_on_push: true
    build_command: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    run_command: gunicorn ptf.wsgi
    routes:
      - path: /
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: ptf.settings
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: changeme-secret-key
      - key: ALLOWED_HOSTS
        value: ptf-app.ondigitalocean.app
      # Optional if using DO managed PostgreSQL
      - key: DATABASE_URL
        value: postgres://user:password@db:5432/ptf_db
