services:
  - name: ptf-backend
    build_command: pip install -r requirements.txt && python manage.py migrate
    run_command: gunicorn ptf.wsgi:application --bind 0.0.0.0:8080 --log-file -
    environment_slug: python
    http_port: 8080
    source_dir: backend
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    github:
      repo: am-muhwezi/ptf
      branch: main
      deploy_on_push: true
    routes:
      - path: /api
    envs:
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: ${ptf_db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_SECRET_KEY
        value: >-
          EV[1:oggZhNNqlerBDrke+oFeGQQxPJQn+3tP:hPBeBgBERFN03rx6VQBG7fzY+39z+8nr9iNZIwFoSx5nbL6ZmjVZSUriBx9SwOxG]
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DISABLE_COLLECTSTATIC
        value: '1'
        scope: RUN_AND_BUILD_TIME