# Generated by Django 5.2.3 on 2025-07-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=50, unique=True)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[("indoor", "Indoor"), ("outdoor", "Outdoor")],
                        default="indoor",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Bi-Annual", "Bi-Annual"),
                            ("Annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Couple", "Couple"),
                            ("Corporate", "Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
