# Generated by Django 5.2.3 on 2025-08-21 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("plan_code", models.CharField(max_length=50, unique=True)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[("indoor", "Indoor"), ("outdoor", "Outdoor")],
                        max_length=10,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Drop-in"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("1_session_week", "1 Session/Week"),
                            ("2_sessions_week", "2 Sessions/Week"),
                            ("3_sessions_week", "3 Sessions/Week"),
                            ("4_sessions_week", "4 Sessions/Week"),
                            ("5_sessions_week", "5 Sessions/Week"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sessions_per_week", models.PositiveIntegerField(default=1)),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=4, help_text="Plan duration in weeks"
                    ),
                ),
                (
                    "weekly_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "per_session_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="For drop-in sessions",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["membership_type", "sessions_per_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_code", "membership_type"),
                        name="unique_plan_per_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_sessions_allowed", models.PositiveIntegerField()),
                ("sessions_used", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("overdue", "Overdue"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for outdoor memberships",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="members.location",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="members.member",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="memberships.membershipplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_used", models.DateTimeField(auto_now_add=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Session"),
                            ("trial", "Trial Session"),
                            ("makeup", "Make-up Session"),
                            ("complimentary", "Complimentary Session"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to="memberships.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_used"],
            },
        ),
    ]
